version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
    entrypoint:
      - node
      - ./ganache-core.docker.cli.js
      #- --mnemonic=
      - --host=0.0.0.0
      - --port=8545
      - --gasLimit=7992181
      - --gasPrice=1000000000
      - --defaultBalanceEther=1000