version: "3.8"

networks:
  nginx_network:
    external:
      name: nginx_network

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 'gy.docker.compose.io'
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://gy.docker.compose.io:8929'
#        gitlab_rails['gitlab_shell_ssh_port'] = 2224
#    ports:
#      - '80:80'
#      - '443:443'
    networks:
      - nginx_network
    volumes:
      - './containers/gitlab/config:/etc/gitlab'
      - './containers/gitlab/logs:/var/log/gitlab'
      - './containers/gitlab/data:/var/opt/gitlab'
