version: '3.8'

networks:
  nginx_network:
    external:
      name: nginx_network

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./containers/nginx:/etc/nginx
      - ./src/sites-available/:/etc/nginx/sites-available/
      - ./src/sites-enabled/:/etc/nginx/sites-enabled/
      - ./src/nginx.conf:/etc/nginx/nginx.conf
#      - ./containers/.static_root/:/static/
#      - ./containers/certbot/conf:/etc/letsencrypt
#      - ./containers/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
      - "12301:12301"
      - "12302:12302"
    networks:
      - nginx_network
#    depends_on:
#      - certbot
#    command : "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes :
#      - ./containers/certbot/conf:/etc/letsencrypt
#      - ./containers/certbot/www:/var/www/certbot
#    entrypoint : "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
