version: '3.8'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfs
    volumes:
      - ./containers/ipfs:/ipfs
    restart: always
    ports:
      - "4001:4001"
      - "8081:8080"

  ipfs_private:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-private
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfs_private
    volumes:
      - ./containers/ipfs_private:/ipfs_private
    restart: always
