version: '3.8'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: go-ipfs
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfs
    volumes:
      - ./ipfs:/ipfs
    restart: always
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"

  ipfs_private:
    image: ipfs/go-ipfs:latest
    container_name: go-ipfs-private
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfs_private
    volumes:
      - ./ipfs_private:/ipfs_private
    restart: always
