version: '3.8'

networks:
  nginx_network:
    external:
      name: nginx_network

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfs
    volumes:
      - ./containers/ipfs:/ipfs
    restart: always
    ports:
      - "5001:5001"
      - "4001:4001"
      - "8081:8080"
    networks:
      - nginx_network
